databases:
  - name: cnc3db
    plan: free
    databaseName: cnc3
    user: cnc3

services:
  - type: web
    plan: free
    name: cnc3
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn cnc3.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cnc3db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4