# Generated by Django 5.2.6 on 2025-09-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=80)),
                ('revision', models.CharField(blank=True, max_length=10)),
                ('file', models.FileField(upload_to='programs/')),
                ('units', models.CharField(default='mm', max_length=2)),
                ('abs_mode', models.BooleanField(default=True)),
                ('bbox_json', models.JSONField(default=dict)),
                ('meta_json', models.JSONField(default=dict)),
                ('est_time_s', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
