# Generated by Django 5.2.6 on 2025-09-11 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('max_rpm', models.IntegerField(default=12000)),
                ('max_feed', models.IntegerField(default=4000)),
                ('rapid_xy', models.IntegerField(default=3000)),
                ('rapid_z', models.IntegerField(default=1500)),
                ('safe_z', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('hardness', models.CharField(blank=True, max_length=40)),
                ('feedspeeds_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_lwh_mm', models.JSONField(default=dict)),
                ('qty', models.IntegerField(default=1)),
                ('wcs', models.CharField(default='G54', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.program')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.material')),
            ],
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
