# Generated by Django 5.2.6 on 2025-09-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_machine_material_job_runlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='program_versions/')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main_app.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
