# Generated by Django 5.2.6 on 2025-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_attachment_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='program',
            name='file_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='file_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='programversion',
            name='file_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programversion',
            name='file_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='programversion',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='programversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='program_versions/'),
        ),
    ]
