# Generated by Django 5.2.6 on 2025-09-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_program_options_program_file_bytes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='file_bytes',
            new_name='file_blob',
        ),
        migrations.RenameField(
            model_name='programversion',
            old_name='file_bytes',
            new_name='file_blob',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
